INSERT INTO `hobbies` (`created_at`, `updated_at`, `deleted_at`, `name`) VALUES
    (now(), now(), NULL, 'Автомобили'),
    (now(), now(), NULL, 'Ароматерапия'),
    (now(), now(), NULL, 'Астрономия'),
    (now(), now(), NULL, 'Аэробика'),
    (now(), now(), NULL, 'Аэрография'),
    (now(), now(), NULL, 'Бадминтон'),
    (now(), now(), NULL, 'Батик'),
    (now(), now(), NULL, 'Батут'),
    (now(), now(), NULL, 'Бег'),
    (now(), now(), NULL, 'Бильярд'),
    (now(), now(), NULL, 'Блоггерство'),                                                                             (now(), now(), NULL, 'Программирование'),
    (now(), now(), NULL, 'Бодиарт'),
    (now(), now(), NULL, 'Боевые искусства (борьба, бокс, рукопашный бой, тайский бокс,…)'),
    (now(), now(), NULL, 'Бонсай'),
    (now(), now(), NULL, 'Боулинг'),
    (now(), now(), NULL, 'Велосипед'),
    (now(), now(), NULL, 'Видеомонтаж'),
    (now(), now(), NULL, 'Выращивание кристаллов'),
    (now(), now(), NULL, 'Выращивание растений и цветов'),
    (now(), now(), NULL, 'Вязание'),
    (now(), now(), NULL, 'Гербарий'),
    (now(), now(), NULL, 'Головоломки'),
    (now(), now(), NULL, 'Гольф'),
    (now(), now(), NULL, 'Горные лыжи'),
    (now(), now(), NULL, 'Граффити'),
    (now(), now(), NULL, 'Дайвинг'),
    (now(), now(), NULL, 'Дартс'),                                                                             (now(), now(), NULL, 'Программирование'),
    (now(), now(), NULL, 'Декупаж'),
    (now(), now(), NULL, 'Дерево (выжигание и резьба)'),
    (now(), now(), NULL, 'Диггерство'),
    (now(), now(), NULL, 'Дизайн интерьера'),
    (now(), now(), NULL, 'Дизайн одежды'),
    (now(), now(), NULL, 'Животные (разведение и уход)'),
    (now(), now(), NULL, 'Жонглирование'),
    (now(), now(), NULL, 'Зентангл'),
    (now(), now(), NULL, 'Игра на музыкальных инструментах (пианино, гитара, труба,…)'),
    (now(), now(), NULL, 'Игрушки и куклы'),
    (now(), now(), NULL, 'Игры на компьютерах и приставках'),
    (now(), now(), NULL, 'Изделия из металла и кузнечное дело'),
    (now(), now(), NULL, 'Изучение новых компьютерных программ'),
    (now(), now(), NULL, 'Икебана'),
    (now(), now(), NULL, 'Иностранные языки'),
    (now(), now(), NULL, 'Йога'),                                                                             (now(), now(), NULL, 'Программирование'),
    (now(), now(), NULL, 'Исторические реконструкции'),
    (now(), now(), NULL, 'Кайтинг'),
    (now(), now(), NULL, 'Каллиграфия'),
    (now(), now(), NULL, 'Карвинг'),
    (now(), now(), NULL, 'Картинг и квадроциклы'),
    (now(), now(), NULL, 'Квест-комнаты'),
    (now(), now(), NULL, 'Кладоискательство и археология'),
    (now(), now(), NULL, 'Клубный отдых'),
    (now(), now(), NULL, 'Коллекционирование'),
    (now(), now(), NULL, 'Компьютерная графика (дизайн, 3D, flash, спецэффекты и т.д.)'),
    (now(), now(), NULL, 'Концерты (посещение)'),
    (now(), now(), NULL, 'Коньки и ролики'),
    (now(), now(), NULL, 'Косплей'),
    (now(), now(), NULL, 'Кроссворды (составление и разгадывание)'),
    (now(), now(), NULL, 'Кулинария'),
    (now(), now(), NULL, 'Лазертаг'),                                                                             (now(), now(), NULL, 'Программирование'),
    (now(), now(), NULL, 'Лепка'),
    (now(), now(), NULL, 'Лошади (верховая езда, уход)'),
    (now(), now(), NULL, 'Лыжи'),
    (now(), now(), NULL, 'Массаж'),
    (now(), now(), NULL, 'Моделирование (самолёты, корабли, воздушные змеи, из спичек, из дерева,…)'),
    (now(), now(), NULL, 'Музеи и выставки'),
    (now(), now(), NULL, 'Музыка (написание, ремиксы)'),
    (now(), now(), NULL, 'Мыловарение'),
    (now(), now(), NULL, 'Настольные игры'),
    (now(), now(), NULL, 'Оригами'),
    (now(), now(), NULL, 'Открытки (изготовление своими руками, обмен (посткроссинг))'),
    (now(), now(), NULL, 'Охота'),
    (now(), now(), NULL, 'Паззлы'),
    (now(), now(), NULL, 'Парашютный спорт'),
    (now(), now(), NULL, 'Паркур'),
    (now(), now(), NULL, 'Пейнтбол'),                                                                             (now(), now(), NULL, 'Программирование'),
    (now(), now(), NULL, 'Пение и караоке'),
    (now(), now(), NULL, 'Переписка по обычной почте'),
    (now(), now(), NULL, 'Петанк'),
    (now(), now(), NULL, 'Пикап'),
    (now(), now(), NULL, 'Пилатес'),
    (now(), now(), NULL, 'Писательская деятельность и журналистика'),
    (now(), now(), NULL, 'Плавание'),
    (now(), now(), NULL, 'Плетение (бисер, корзины, коробочки, кружева, макраме…)'),
    (now(), now(), NULL, 'Получение научных званий и степеней'),
    (now(), now(), NULL, 'Предпринимательство'),
    (now(), now(), NULL, 'Программирование'),
    (now(), now(), NULL, 'Психология и тренинги'),
    (now(), now(), NULL, 'Путешествия (другие страны, альпинизм, походы)'),
    (now(), now(), NULL, 'Пчеловодство'),
    (now(), now(), NULL, 'Радиовещание (подкасты, интернет-радиостанции, радиопередатчики)'),
    (now(), now(), NULL, 'Разработка сайтов'),                                                                             (now(), now(), NULL, 'Программирование'),
    (now(), now(), NULL, 'Рисование (акварель, холст, бумага, карандаши, стекло, гуашь и т.п.)'),
    (now(), now(), NULL, 'Рисование по номерам'),
    (now(), now(), NULL, 'Робототехника'),
    (now(), now(), NULL, 'Рукоделия из кожи (одежда, аксессуары)'),
    (now(), now(), NULL, 'Рыбалка'),
    (now(), now(), NULL, 'Самодельные (handmade) вещи: одежда, обувь, аксессуары'),
    (now(), now(), NULL, 'Серфинг'),
    (now(), now(), NULL, 'Силовые тренировки'),
    (now(), now(), NULL, 'Скейтборд'),
    (now(), now(), NULL, 'Скрапбукинг (фотоальбомы своими руками)'),
    (now(), now(), NULL, 'Сноуборд'),
    (now(), now(), NULL, 'Собирание грибов и ягод'),
    (now(), now(), NULL, 'Спорт-фанат'),
    (now(), now(), NULL, 'Стекло (изготовление украшений и предметов интерьера)'),
    (now(), now(), NULL, 'Страйкбол'),
    (now(), now(), NULL, 'Стрельба'),                                                                             (now(), now(), NULL, 'Программирование'),
    (now(), now(), NULL, 'Танцы и балет'),
    (now(), now(), NULL, 'Татуировки и пирсинг'),
    (now(), now(), NULL, 'Театр (театральный кружок)'),
    (now(), now(), NULL, 'Теннис'),
    (now(), now(), NULL, 'Файер-шоу'),
    (now(), now(), NULL, 'Фейерверки'),
    (now(), now(), NULL, 'Фокусы'),
    (now(), now(), NULL, 'Фотография и фотокниги'),
    (now(), now(), NULL, 'Футбол'),
    (now(), now(), NULL, 'Шитье и вышивание');

INSERT INTO `shops` (`created_at`, `updated_at`, `deleted_at`, `name`) VALUES
    (now(), now(), NULL, 'Мвидео');

INSERT INTO `gifts` (`created_at`, `updated_at`, `deleted_at`, `name`, `gender`, `age_start`, `age_end`) VALUES
    (now(), now(), NULL, 'Смарт-часы Apple Watch SE GPS 44mm', 'unisex', '14', '65');

INSERT INTO `gift_has_hobbies` (`gift_id`, `hobby_id`) VALUES
    ('2', '92'),
    ('2', '97');

INSERT INTO `images` (`created_at`, `updated_at`, `deleted_at`, `gift_id`, `url`) VALUES
    (now(), now(), NULL, '2', 'https://img.mvideo.ru/Big/30059179bb.jpg'),
    (now(), now(), NULL, '2', 'https://img.mvideo.ru/Big/30059179bb1.jpg'),
    (now(), now(), NULL, '2', 'https://img.mvideo.ru/Big/30059179bb2.jpg');

INSERT INTO `products` (`created_at`, `updated_at`, `deleted_at`, `gift_id`, `shop_id`, `name`, `price`, `url`) VALUES
    (now(), now(), NULL, '2', '1', 'Смарт-часы Apple Watch SE GPS 44mm Gold Aluminium/Starlight Sport', '24990', 'https://www.mvideo.ru/products/smart-chasy-apple-watch-se-gps-44mm-gold-aluminium-starlight-sport-30059179'),
    (now(), now(), NULL, '2', '2', 'Смарт-часы Apple Watch SE GPS 44mm', '24990', 'https://www.dns-shop.ru/product/6ecd119ff7c71b80/smart-casy-apple-watch-se-gps-44mm/');

